package ru.transora.app.scheduling

import org.springframework.context.annotation.Lazy
import org.slf4j.LoggerFactory
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import ru.transora.app.sales.TicketRepository
import ru.transora.scheduling.domain.ScheduleEntry
import ru.transora.scheduling.domain.ScheduleType
import ru.transora.scheduling.domain.ScheduleWithEntries
import ru.transora.scheduling.domain.Trip
import ru.transora.scheduling.domain.TripStatus
import java.time.Clock
import java.time.LocalDate
import java.time.ZoneId
import java.time.ZonedDateTime
import java.util.UUID

data class TripGenerationResult(
    val fromDate: LocalDate,
    val toDate: LocalDate,
    val createdCount: Int,
    val skippedCount: Int,
    val cancelledCount: Int = 0,
)

@Service
class TripGenerationService(
    private val scheduleRepository: ScheduleRepository,
    private val routeRepository: RouteRepository,
    private val serviceStationRepository: ServiceStationRepository,
    private val vehicleRepository: VehicleRepository,
    private val tripRepository: TripRepository,
    private val tripStopPlanner: TripStopPlanner,
    private val ticketRepository: TicketRepository,
    @Lazy private val tripService: TripService,
    private val schedulingEventPublisher: SchedulingEventPublisher,
    private val schedulingProperties: SchedulingProperties,
) {
    private val log = LoggerFactory.getLogger(javaClass)

    @Transactional
    fun generate(
        fromDate: LocalDate? = null,
        horizonDays: Int? = null,
        stationId: UUID? = null,
        routeId: UUID? = null,
    ): TripGenerationResult {
        val start = fromDate ?: LocalDate.now(Clock.systemUTC())
        val horizon = horizonDays ?: schedulingProperties.generationHorizonDays
        val end = start.plusDays(horizon.toLong() - 1)
        var created = 0
        var skipped = 0
        var cancelled = 0

        val schedules = scheduleRepository.listActiveWithEntries()
            .filter { stationId == null || routePassesStation(it.schedule.routeId, stationId) }
            .filter { routeId == null || it.schedule.routeId == routeId }

        var date = start
        while (!date.isAfter(end)) {
            val winners = selectWinningEntries(schedules, date)
            for ((key, candidate) in winners) {
                val routeId = key.first
                val tripNumber = key.second
                val existing = tripRepository.findByRouteDateTripNumber(routeId, date, tripNumber)

                if (existing != null) {
                    if (existing.scheduleEntryId == candidate.entry.id) {
                        skipped++
                        continue
                    }
                    if (existing.autoGenerated) {
                        if (ticketRepository.countIssuedByTripId(existing.id) > 0) {
                            log.warn(
                                "Skipping regeneration for trip {} on {} — tickets exist",
                                existing.id,
                                date,
                            )
                            skipped++
                            continue
                        }
                        runCatching {
                            tripService.cancelTripIfAllowed(existing.id, "Superseded by schedule priority")
                            cancelled++
                        }.onFailure { ex ->
                            log.warn("Could not cancel superseded trip {}: {}", existing.id, ex.message)
                            skipped++
                            continue
                        }
                    } else {
                        skipped++
                        continue
                    }
                }

                createGeneratedTrip(candidate.scheduleWithEntries, candidate.entry, date)
                created++
            }
            date = date.plusDays(1)
        }

        return TripGenerationResult(start, end, created, skipped, cancelled)
    }

    private fun routePassesStation(routeId: UUID, stationId: UUID): Boolean {
        val route = routeRepository.findWithStops(routeId) ?: return false
        return route.stops.any { it.stationId == stationId }
    }

    private data class EntryCandidate(
        val scheduleWithEntries: ScheduleWithEntries,
        val entry: ScheduleEntry,
    )

    private fun selectWinningEntries(
        schedules: List<ScheduleWithEntries>,
        date: LocalDate,
    ): Map<Pair<UUID, String>, EntryCandidate> {
        val dayOfWeek = date.dayOfWeek.value
        val candidates = mutableListOf<EntryCandidate>()

        for (scheduleWithEntries in schedules) {
            val schedule = scheduleWithEntries.schedule
            if (!scheduleAppliesOnDate(schedule.scheduleType, schedule.validFrom, schedule.validTo, date)) {
                continue
            }
            for (entry in scheduleWithEntries.entries) {
                if (!entry.isActive || dayOfWeek !in entry.daysOfWeek) {
                    continue
                }
                candidates += EntryCandidate(scheduleWithEntries, entry)
            }
        }

        return candidates
            .groupBy { Pair(it.scheduleWithEntries.schedule.routeId, it.entry.tripNumber) }
            .mapValues { (_, group) ->
                group.maxBy { it.scheduleWithEntries.schedule.scheduleType.priority() }
            }
    }

    private fun scheduleAppliesOnDate(
        type: ScheduleType,
        validFrom: LocalDate?,
        validTo: LocalDate?,
        date: LocalDate,
    ): Boolean =
        when (type) {
            ScheduleType.PERMANENT -> true
            ScheduleType.SEASONAL -> validFrom != null && validTo != null &&
                !date.isBefore(validFrom) && !date.isAfter(validTo)
            ScheduleType.EXCEPTION -> validFrom != null && date == validFrom
        }

    private fun createGeneratedTrip(
        scheduleWithEntries: ScheduleWithEntries,
        entry: ScheduleEntry,
        tripDate: LocalDate,
    ) {
        val routeWithStops = routeRepository.findWithStops(scheduleWithEntries.schedule.routeId)
            ?: throw IllegalStateException("Route ${scheduleWithEntries.schedule.routeId} not found")
        val stops = routeWithStops.stops
        if (stops.isEmpty()) {
            return
        }

        val firstStop = stops.first()
        val lastStop = stops.last()
        val departureStationCode = firstStop.stationId?.let { stationId ->
            serviceStationRepository.findById(stationId)?.code
        } ?: "T1"

        val zoneId = firstStop.stationId?.let { stationId ->
            serviceStationRepository.findById(stationId)?.timezone
        }?.let { ZoneId.of(it) } ?: ZoneId.of("Europe/Moscow")

        val departureInstant = ZonedDateTime.of(tripDate, entry.departureTime, zoneId).toInstant()
        val now = Clock.systemUTC().instant()
        val tripId = UUID.randomUUID()

        val trip = Trip(
            id = tripId,
            routeNumber = entry.tripNumber,
            departureStation = firstStop.stopName,
            arrivalStation = lastStop.stopName,
            departureStationCode = departureStationCode,
            departureTime = departureInstant,
            expectedDepartureTime = departureInstant,
            delayMinutes = null,
            platform = null,
            status = TripStatus.PLANNED,
            createdAt = now,
            routeId = routeWithStops.route.id,
            vehicleId = entry.defaultVehicleId,
            driverId = null,
            tripDate = tripDate,
            tripNumber = entry.tripNumber,
            autoGenerated = true,
            scheduleEntryId = entry.id,
        )

        tripRepository.insertGenerated(trip)
        tripStopPlanner.createTripStops(tripId, stops, tripDate, entry.departureTime, zoneId)

        val seatCount = entry.defaultVehicleId?.let { vehicleId ->
            vehicleRepository.findById(vehicleId)?.totalSeats
        } ?: return

        schedulingEventPublisher.publish(
            eventType = "scheduling.trip.created",
            tripId = tripId,
            payload = mapOf(
                "tripId" to tripId.toString(),
                "routeId" to routeWithStops.route.id.toString(),
                "routeNumber" to entry.tripNumber,
                "tripNumber" to entry.tripNumber,
                "departureStationCode" to departureStationCode,
                "tripDate" to tripDate.toString(),
                "seatCount" to seatCount,
                "autoGenerated" to true,
            ),
        )
    }
}

private fun ScheduleType.priority(): Int =
    when (this) {
        ScheduleType.EXCEPTION -> 3
        ScheduleType.SEASONAL -> 2
        ScheduleType.PERMANENT -> 1
    }
