package ru.transora.app.scheduling

import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.tags.Tag
import jakarta.validation.Valid
import jakarta.validation.constraints.Future
import jakarta.validation.constraints.Max
import jakarta.validation.constraints.Min
import jakarta.validation.constraints.NotBlank
import org.springframework.format.annotation.DateTimeFormat
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PatchMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController
import ru.transora.app.iam.security.RequirePermission
import ru.transora.iam.permissions.Permissions
import ru.transora.scheduling.domain.Trip
import ru.transora.scheduling.domain.TripStatus
import java.time.Instant
import java.time.LocalDate
import java.time.LocalTime
import java.util.UUID

@RestController
@RequestMapping("/api/trips")
@Tag(name = "Trips", description = "Trip scheduling and lifecycle")
class TripController(
    private val tripService: TripService,
) {
    @PostMapping
    @RequirePermission(Permissions.SCHEDULE_CREATE)
    @Operation(summary = "Create a flat trip with seats (legacy slice)")
    fun create(@Valid @RequestBody request: CreateTripRequest): TripResponse =
        tripService.createTrip(request).toResponse()

    @PostMapping("/from-route")
    @RequirePermission(Permissions.SCHEDULE_CREATE)
    @Operation(summary = "Create a trip from route template with stops")
    fun createFromRoute(@Valid @RequestBody request: CreateTripFromRouteRequest): TripResponse =
        tripService.createTripFromRoute(request).toResponse()

    @GetMapping
    @RequirePermission(Permissions.SCHEDULE_VIEW)
    @Operation(summary = "List trips with optional filters")
    fun list(
        @RequestParam(required = false) stationCode: String?,
        @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) from: Instant?,
        @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) to: Instant?,
        @RequestParam(defaultValue = "3") @Min(1) @Max(24) horizonHours: Int,
        @RequestParam(defaultValue = "100") @Min(1) @Max(500) limit: Int,
    ): List<TripResponse> =
        tripService.listTrips(
            TripListFilter(
                stationCode = stationCode,
                from = from,
                to = to,
                horizonHours = horizonHours,
                limit = limit,
            ),
        ).map { it.toResponse() }

    @GetMapping("/{tripId}")
    @RequirePermission(Permissions.SCHEDULE_VIEW)
    @Operation(summary = "Get trip by id")
    fun get(
        @PathVariable tripId: UUID,
        @RequestParam(required = false) include: String?,
    ): TripDetailResponse {
        val detail = tripService.getTrip(tripId, includeStops = include == "stops")
        return detail.toResponse()
    }

    @PatchMapping("/{tripId}")
    @RequirePermission(Permissions.SCHEDULE_EDIT)
    @Operation(summary = "Update trip status, platform, delay, vehicle, or driver")
    fun update(
        @PathVariable tripId: UUID,
        @Valid @RequestBody request: UpdateTripRequest,
    ): TripResponse =
        tripService.updateTrip(tripId, request).toResponse()
}

data class CreateTripRequest(
    @field:NotBlank val routeNumber: String,
    @field:NotBlank val departureStation: String,
    @field:NotBlank val arrivalStation: String,
    val departureStationCode: String? = null,
    @field:Future val departureTime: Instant,
    val platform: String?,
    @field:Min(1) @field:Max(80) val seatCount: Int,
)

data class UpdateTripRequest(
    val expectedDepartureTime: Instant? = null,
    val delayMinutes: Int? = null,
    val delayReason: String? = null,
    val platform: String? = null,
    val status: TripStatus? = null,
    val vehicleId: UUID? = null,
    val driverId: UUID? = null,
)

data class TripResponse(
    val id: String,
    val routeNumber: String,
    val tripNumber: String?,
    val departureStation: String,
    val arrivalStation: String,
    val departureStationCode: String,
    val departureTime: Instant,
    val expectedDepartureTime: Instant,
    val delayMinutes: Int?,
    val platform: String?,
    val status: String,
    val routeId: String?,
    val tripDate: LocalDate?,
    val vehicleId: String?,
    val driverId: String?,
    val autoGenerated: Boolean,
)

data class TripDetailResponse(
    val trip: TripResponse,
    val stops: List<TripStopResponse>,
)

private fun Trip.toResponse(): TripResponse =
    TripResponse(
        id = id.toString(),
        routeNumber = routeNumber,
        tripNumber = tripNumber ?: routeNumber,
        departureStation = departureStation,
        arrivalStation = arrivalStation,
        departureStationCode = departureStationCode,
        departureTime = departureTime,
        expectedDepartureTime = expectedDepartureTime,
        delayMinutes = delayMinutes,
        platform = platform,
        status = status.name,
        routeId = routeId?.toString(),
        tripDate = tripDate,
        vehicleId = vehicleId?.toString(),
        driverId = driverId?.toString(),
        autoGenerated = autoGenerated,
    )

private fun TripDetail.toResponse(): TripDetailResponse =
    TripDetailResponse(
        trip = trip.toResponse(),
        stops = stops.map { it.toResponse() },
    )

private fun ru.transora.scheduling.domain.TripStop.toResponse() = TripStopResponse(
    id = id.toString(),
    tripId = tripId.toString(),
    stopOrder = stopOrder,
    stopName = stopName,
    stationId = stationId?.toString(),
    isExternal = isExternal,
    scheduledArrival = scheduledArrival,
    scheduledDeparture = scheduledDeparture,
    estimatedArrival = estimatedArrival,
    estimatedDeparture = estimatedDeparture,
    actualArrival = actualArrival,
    actualDeparture = actualDeparture,
    stopStatus = stopStatus.name,
)
