package ru.transora.app.scheduling

import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.stereotype.Repository
import ru.transora.scheduling.domain.Trip
import ru.transora.scheduling.domain.TripStatus
import java.sql.ResultSet
import java.sql.Timestamp
import java.time.Instant
import java.time.LocalDate
import java.util.UUID

data class TripFilter(
    val stationCode: String? = null,
    val from: Instant? = null,
    val to: Instant? = null,
    val limit: Int = 100,
)

@Repository
class TripRepository(
    private val jdbc: JdbcTemplate,
) {
    fun insert(trip: Trip) {
        jdbc.update(
            """
            INSERT INTO scheduling.trips (
                id, route_number, departure_station, arrival_station,
                departure_station_code, departure_time, expected_departure_time,
                delay_minutes, platform, status, created_at,
                route_id, vehicle_id, driver_id, trip_date, trip_number,
                auto_generated, schedule_entry_id
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """.trimIndent(),
            trip.id,
            trip.routeNumber,
            trip.departureStation,
            trip.arrivalStation,
            trip.departureStationCode,
            Timestamp.from(trip.departureTime),
            Timestamp.from(trip.expectedDepartureTime),
            trip.delayMinutes,
            trip.platform,
            trip.status.name,
            Timestamp.from(trip.createdAt),
            trip.routeId,
            trip.vehicleId,
            trip.driverId,
            trip.tripDate?.let { java.sql.Date.valueOf(it) },
            trip.tripNumber ?: trip.routeNumber,
            trip.autoGenerated,
            trip.scheduleEntryId,
        )
    }

    fun insertGenerated(trip: Trip) = insert(trip)

    fun existsByScheduleEntryAndDate(scheduleEntryId: UUID, tripDate: LocalDate): Boolean {
        val count = jdbc.queryForObject(
            """
            SELECT COUNT(*) FROM scheduling.trips
            WHERE schedule_entry_id = ? AND trip_date = ?
            """.trimIndent(),
            Int::class.java,
            scheduleEntryId,
            java.sql.Date.valueOf(tripDate),
        ) ?: 0
        return count > 0
    }

    fun existsByRouteDateTripNumber(routeId: UUID, tripDate: LocalDate, tripNumber: String): Boolean {
        val count = jdbc.queryForObject(
            """
            SELECT COUNT(*) FROM scheduling.trips
            WHERE route_id = ? AND trip_date = ? AND trip_number = ?
              AND status != 'CANCELLED'
            """.trimIndent(),
            Int::class.java,
            routeId,
            java.sql.Date.valueOf(tripDate),
            tripNumber,
        ) ?: 0
        return count > 0
    }

    fun findByRouteDateTripNumber(routeId: UUID, tripDate: LocalDate, tripNumber: String): Trip? =
        jdbc.query(
            """
            SELECT * FROM scheduling.trips
            WHERE route_id = ? AND trip_date = ? AND trip_number = ?
              AND status != 'CANCELLED'
            ORDER BY created_at DESC
            LIMIT 1
            """.trimIndent(),
            { rs, _ -> rs.toTrip() },
            routeId,
            java.sql.Date.valueOf(tripDate),
            tripNumber,
        ).firstOrNull()

    fun findById(id: UUID): Trip? =
        jdbc.query(
            "SELECT * FROM scheduling.trips WHERE id = ?",
            { rs, _ -> rs.toTrip() },
            id,
        ).firstOrNull()

    fun findByIdForUpdate(id: UUID): Trip? =
        jdbc.query(
            "SELECT * FROM scheduling.trips WHERE id = ? FOR UPDATE",
            { rs, _ -> rs.toTrip() },
            id,
        ).firstOrNull()

    fun list(): List<Trip> =
        jdbc.query(
            "SELECT * FROM scheduling.trips ORDER BY expected_departure_time",
        ) { rs, _ -> rs.toTrip() }

    fun listFiltered(filter: TripFilter): List<Trip> {
        val conditions = mutableListOf<String>()
        val params = mutableListOf<Any>()

        filter.stationCode?.let {
            conditions += "departure_station_code = ?"
            params += it
        }
        filter.from?.let {
            conditions += "expected_departure_time >= ?"
            params += Timestamp.from(it)
        }
        filter.to?.let {
            conditions += "expected_departure_time <= ?"
            params += Timestamp.from(it)
        }

        val whereClause = if (conditions.isEmpty()) "" else "WHERE ${conditions.joinToString(" AND ")}"
        val sql = """
            SELECT * FROM scheduling.trips
            $whereClause
            ORDER BY expected_departure_time
            LIMIT ?
        """.trimIndent()

        params += filter.limit
        return jdbc.query(sql, { rs, _ -> rs.toTrip() }, *params.toTypedArray())
    }

    fun update(
        id: UUID,
        expectedDepartureTime: Instant,
        delayMinutes: Int?,
        platform: String?,
        status: TripStatus,
    ): Int =
        jdbc.update(
            """
            UPDATE scheduling.trips
            SET expected_departure_time = ?,
                delay_minutes = ?,
                platform = ?,
                status = ?
            WHERE id = ?
            """.trimIndent(),
            Timestamp.from(expectedDepartureTime),
            delayMinutes,
            platform,
            status.name,
            id,
        )

    fun updateStatus(id: UUID, status: TripStatus) {
        jdbc.update(
            "UPDATE scheduling.trips SET status = ? WHERE id = ?",
            status.name,
            id,
        )
    }

    fun updateResources(
        id: UUID,
        vehicleId: UUID?,
        driverId: UUID?,
    ) {
        jdbc.update(
            """
            UPDATE scheduling.trips
            SET vehicle_id = ?, driver_id = ?
            WHERE id = ?
            """.trimIndent(),
            vehicleId,
            driverId,
            id,
        )
    }

    fun findConflictingTrips(
        resourceColumn: String,
        resourceId: UUID,
        intervalStart: Instant,
        intervalEnd: Instant,
        excludeTripId: UUID?,
    ): List<Trip> {
        require(resourceColumn in setOf("vehicle_id", "driver_id")) {
            "resourceColumn must be vehicle_id or driver_id"
        }
        val params = mutableListOf<Any>(
            resourceId,
            Timestamp.from(intervalEnd),
            Timestamp.from(intervalStart),
        )
        val excludeClause = if (excludeTripId != null) {
            params += excludeTripId
            "AND t.id != ?"
        } else {
            ""
        }
        val sql = """
            SELECT t.* FROM scheduling.trips t
            WHERE t.$resourceColumn = ?
              AND t.status NOT IN ('CANCELLED', 'COMPLETED')
              AND t.departure_time < ?
              AND (
                  SELECT COALESCE(ts.actual_arrival, ts.estimated_arrival, ts.scheduled_arrival, ts.scheduled_departure)
                  FROM scheduling.trip_stops ts
                  WHERE ts.trip_id = t.id
                  ORDER BY ts.stop_order DESC
                  LIMIT 1
              ) > ?
              $excludeClause
        """.trimIndent()
        return jdbc.query(sql, { rs, _ -> rs.toTrip() }, *params.toTypedArray())
    }

    fun count(): Int =
        jdbc.queryForObject("SELECT COUNT(*) FROM scheduling.trips", Int::class.java) ?: 0

    private fun ResultSet.toTrip(): Trip {
        val tripDateColumn = runCatching { getDate("trip_date") }.getOrNull()
        return Trip(
            id = getObject("id", UUID::class.java),
            routeNumber = getString("route_number"),
            departureStation = getString("departure_station"),
            arrivalStation = getString("arrival_station"),
            departureStationCode = getString("departure_station_code"),
            departureTime = getTimestamp("departure_time").toInstant(),
            expectedDepartureTime = getTimestamp("expected_departure_time").toInstant(),
            delayMinutes = getObject("delay_minutes") as Int?,
            platform = getString("platform"),
            status = TripStatus.valueOf(getString("status")),
            createdAt = getTimestamp("created_at").toInstant(),
            routeId = runCatching { getObject("route_id") as UUID? }.getOrNull(),
            vehicleId = runCatching { getObject("vehicle_id") as UUID? }.getOrNull(),
            driverId = runCatching { getObject("driver_id") as UUID? }.getOrNull(),
            tripDate = tripDateColumn?.toLocalDate(),
            tripNumber = runCatching { getString("trip_number") }.getOrNull(),
            autoGenerated = runCatching { getBoolean("auto_generated") }.getOrDefault(false),
            scheduleEntryId = runCatching { getObject("schedule_entry_id") as UUID? }.getOrNull(),
        )
    }
}
