package ru.transora.scheduling.domain

import java.time.Instant
import java.time.LocalDate
import java.util.UUID

data class Trip(
    val id: UUID,
    val routeNumber: String,
    val departureStation: String,
    val arrivalStation: String,
    val departureStationCode: String,
    val departureTime: Instant,
    val expectedDepartureTime: Instant,
    val delayMinutes: Int?,
    val platform: String?,
    val status: TripStatus,
    val createdAt: Instant,
    val routeId: UUID? = null,
    val vehicleId: UUID? = null,
    val driverId: UUID? = null,
    val tripDate: LocalDate? = null,
    val tripNumber: String? = null,
    val autoGenerated: Boolean = false,
    val scheduleEntryId: UUID? = null,
)

enum class TripStatus {
    PLANNED,
    OPEN,
    BOARDING,
    DEPARTED,
    IN_TRANSIT,
    ARRIVED,
    COMPLETED,
    CANCELLED,
}
